version: '3.8'
services:
  tide_api:
    build:
      context: ./backend
    container_name: tide_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@tide_postgres:5432/tide_db
      - MODEL_CHECKPOINT_PATH=/app/ml/checkpoints/full_checkpoint2.pth
    volumes:
      - ./backend:/app
    depends_on:
      - tide_postgres
    restart: unless-stopped

  tide_postgres:
    image: postgis/postgis:15-3.3
    container_name: tide_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tide_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  tide_redis:
    image: redis:7-alpine
    container_name: tide_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  tide_frontend:
    build:
      context: ./frontend
    container_name: tide_frontend
    ports:
      - "80:80"
    depends_on:
      - tide_api
    restart: unless-stopped

volumes:
  postgres_data:
